////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc
////
= Quarkus - Using Security with Jdbc realm

include::./attributes.adoc[]

This guide demonstrates how your Quarkus application can use a database to store your user identities.


== Prerequisites

To complete this guide, you need:

* less than 15 minutes
* an IDE
* JDK 1.8+ installed with `JAVA_HOME` configured appropriately
* Apache Maven 3.5.3+

== Architecture

In this example, we build a very simple microservice which offers three endpoints:

* `/api/public`
* `/api/users/me`
* `/api/admin`

The `/api/public` endpoint can be accessed anonymously.
The `/api/admin` endpoint is also protected with RBAC (Role-Based Access Control) where only users granted with the `admin` role can access. At this endpoint, we use the `@RolesAllowed` annotation to declaratively enforce the access constraint.
The `/api/users/me` endpoint is protected with RBAC (Role-Based Access Control) where only users granted with the `user` role can access. As a response, it returns a JSON document with details about the user.

== Solution

We recommend that you follow the instructions in the next sections and create the application step by step.
However, you can go right to the completed example.

Clone the Git repository: `git clone {quickstarts-clone-url}`, or download an {quickstarts-archive-url}[archive].

The solution is located in the `using-elytron-security-jdbc` {quickstarts-tree-url}/using-elytron-security-jdbc[directory].

== Creating the Maven Project

First, we need a new project. Create a new project with the following command:

[source, subs=attributes+]
----
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=using-elytron-security-jdbc \
    -Dextensions="elytron-security-jdbc, jdbc-h2, resteasy"
----

[NOTE]
====
Don't forget to to add the database connector library of choice. Here we are using H2 as identity store.
====

This command generates a Maven project, importing the `elytron-security-jdbc` extension
which is an [`wildfly-elytron-realm-jdbc`](https://docs.wildfly.org/17/WildFly_Elytron_Security.html#jdbc-security-realm) adapter for Quarkus applications.

== Writing the application

Let's start by implementing the `/api/public` endpoint. As you can see from the source code below it is just a regular JAX-RS resource:

[source,java]
----
package org.acme.elytron.security.jdbc;

import javax.annotation.security.PermitAll;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/api/public")
public class PublicResource {

    @GET
    @PermitAll
    @Produces(MediaType.TEXT_PLAIN)
    public String publicResource() {
        return "public";
   }
}
----

The source code for the `/api/admin` endpoint is also very simple. The main difference here is that we are using a `@RolesAllowed` annotation to make sure that only users granted with the `admin` role can access the endpoint:


[source,java]
----
package org.acme.elytron.security.jdbc;

import javax.annotation.security.RolesAllowed;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/api/admin")
public class AdminResource {

    @GET
    @RolesAllowed("admin")
    @Produces(MediaType.TEXT_PLAIN)
    public String adminResource() {
         return "admin";
    }
}

----

For last, the `/api/users/me` endpoint. As you can see from the source code below, we are trusting only users with the `user` role.
We are using `SecurityContext` to get access to the current authenticated Principal and we return the user's name. This information is loaded from the database.

[source,java]
----
package org.acme.elytron.security.jdbc;

import javax.annotation.security.RolesAllowed;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.SecurityContext;

@Path("/api/users")
public class UserResource {

    @GET
    @RolesAllowed("user")
    @Path("/me")
    @Produces(MediaType.APPLICATION_JSON)
    public String me(@Context SecurityContext securityContext) {
        return securityContext.getUserPrincipal().getName();
    }
}
----

=== Configuring the Application

The `elytron-security-jdbc` extension requires at least one datasource to access to you database.

[source,properties]
----
quarkus.datasource.url=jdbc:h2:mem:using-elytron-security-jdbc;DB_CLOSE_DELAY=-1;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:import.sql' <1>
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username=sa
quarkus.datasource.password=sa
----

In our context, we are using H2 in-memory mode as identity store and we load `import.sql` to init the database wit users and roles.

[source,sql]
----
CREATE TABLE test_user (
  id INT,
  username VARCHAR(255),
  password VARCHAR(255),
  role VARCHAR(255)
);

INSERT INTO test_user (id, username, password, role) VALUES (1, 'admin', 'admin', 'admin');
INSERT INTO test_user (id, username, password, role) VALUES (2, 'user','user', 'user');
----

[NOTE]
====
We're sure you know but we kindly remind that you must not store clear password in production environment ;-)
The `elytron-security-jdbc` offers a built-in bcrypt password mapper.
====

We can now configure the Elytron Jdbc Realm.

[source,properties]
----
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.password, u.role FROM test_user u WHERE u.username=? <1>
quarkus.security.jdbc.principal-query.clear-password-mapper.enabled=true <2>
quarkus.security.jdbc.principal-query.clear-password-mapper.password-index=1
quarkus.security.jdbc.principal-query.attribute-mappings.0.index=2 <3>
quarkus.security.jdbc.principal-query.attribute-mappings.0.to=groups
----

The `elytron-security-jdbc` extension requires at least one principal query to trust and load a user identity.

<1> We define a SQL parametrized statement (with exactly 1 parameter) which should return the user's password plus any information your want to load.
<2> We  configure the password mapper with the position of the password field in the `SELECT` fields and other information like salt, hash encoding, etc.
<3> We use `attribute-mappings` to bind the `SELECT` projection fields (ie. `u.role` here) to the target Principal representation attributes.

[NOTE]
====
In the `principal-query` configuration all the `index` properties start at 1 (rather than 0).
====

== Testing the Application

The application is now protected and the identities is provided by our database.
The very first todo is to ensure the anonymous access works.

```bash
$ curl -i -X GET http://localhost:8080/api/public
HTTP/1.1 200 OK
Content-Length: 6
Content-Type: text/plain;charset=UTF-8

public%
```

Now, let's try a to hit a protected resources anonymously.

```bash
$ curl -i -X GET http://localhost:8080/api/admin
HTTP/1.1 401 Unauthorized
Content-Length: 14
Content-Type: text/html;charset=UTF-8

Not authorized%
```

So far, so good,  now let's try with an allowed user.

```bash
$ curl -i -X GET -u admin:admin http://localhost:8080/api/admin
HTTP/1.1 200 OK
Content-Length: 5
Content-Type: text/plain;charset=UTF-8

admin%
```
By providing the `admin:admin` credentials, the extension succeed to authenticate the user and load its roles.
The `admin` user is authorized to access to the protected resources.

The  user the `admin` should be forbid to access a resources protected with `@RolesAllowed("user")` because it hasn't this role.
```bash
$ curl -i -X GET -u admin:admin http://localhost:8080/api/users/me
HTTP/1.1 403 Forbidden
Content-Length: 34
Content-Type: text/html;charset=UTF-8

Access forbidden: role not allowed%
```

Finally, using the user `user` works and the security context contains the principal details (username for instance).
```bash
curl -i -X GET -u user:user http://localhost:8080/api/users/me
HTTP/1.1 200 OK
Content-Length: 4
Content-Type: application/json

user%
```

== Advanced Configuration

This guide only covered an easy use case, the extension offers multiple datasources, multiple principal queries configuration as well as a bcrypt password mapper.

[source,properties]
--
quarkus.datasource.url=jdbc:h2:mem:multiple-data-sources-users;DB_CLOSE_DELAY=-1;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:multiple-data-sources/users.sql'
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username=sa
quarkus.datasource.password=sa

quarkus.datasource.permissions.url=jdbc:h2:mem:multiple-data-sources-permissions;DB_CLOSE_DELAY=-1;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:multiple-data-sources/permissions.sql'
quarkus.datasource.permissions.driver=org.h2.Driver
quarkus.datasource.permissions.username=sa
quarkus.datasource.permissions.password=sa

quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.password FROM test_user u WHERE u.username=?
quarkus.security.jdbc.principal-query.clear-password-mapper.enabled=true
quarkus.security.jdbc.principal-query.clear-password-mapper.password-index=1

quarkus.security.jdbc.principal-query.roles.sql=SELECT r.role_name FROM test_role r, test_user_role ur WHERE ur.username=? AND ur.role_id = r.id
quarkus.security.jdbc.principal-query.roles.datasource=permissions
quarkus.security.jdbc.principal-query.roles.attribute-mappings.0.index=1
quarkus.security.jdbc.principal-query.roles.attribute-mappings.0.to=groups
--

All the configuration options are detailled bellow.

|===
|Property Name|Default|Description
|quarkus.security.file.enabled|false|Determine whether security via the file realm is enabled
|quarkus.security.jdbc.principal-query.sql| |The sql query to find the password, the statement can be parametrized and accept only one argument
|quarkus.security.jdbc.principal-query.datasource|null| The datasource name, if null uses Agroal's default datasource
|quarkus.security.jdbc.principal-query.clear-password-mapper.enabled|false|If the clear-password-mapper is enabled.
|quarkus.security.jdbc.principal-query.clear-password-mapper.password-index|1|The index (1 based numbering) of the column containing the password hash
|quarkus.security.jdbc.principal-query.bcrypt-password-mapper.enabled|false|If the bcrypt-password-mapper is enabled.
|quarkus.security.jdbc.principal-query.bcrypt-password-mapper.password-index|1|The index (1 based numbering) of the column containing the password hash
|quarkus.security.jdbc.principal-query.hashEncoding|BASE64|The password hash encoding ("BASE64" or "HEX")
|quarkus.security.jdbc.principal-query.saltIndex| |The index (1 based numbering) of the column containing the password salt
|quarkus.security.jdbc.principal-query.saltEncoding|BASE64|The salt encoding ("BASE64" or "HEX")
|quarkus.security.jdbc.principal-query.roles.attribute-mappings."<named-attribute-mapping>".index|N/A| The index (1 based numbering) of column to map
|quarkus.security.jdbc.principal-query.roles.attribute-mappings."<named-attribute-mapping>".to|N/A| The target attribute name
|quarkus.security.file.enabled|false|Determine whether security via the file realm is enabled
|quarkus.security.jdbc.principal-query."<name-principal-query>".sql| |The sql query to find the password, the statement can be parametrized and accept only one argument
|quarkus.security.jdbc.principal-query."<name-principal-query>".datasource|null| The datasource name, if null uses Agroal's default datasource
|quarkus.security.jdbc.principal-query."<name-principal-query>".clear-password-mapper.enabled|false|If the clear-password-mapper is enabled.
|quarkus.security.jdbc.principal-query."<name-principal-query>".clear-password-mapper.password-index|1|The index (1 based numbering) of the column containing the password hash
|quarkus.security.jdbc.principal-query."<name-principal-query>".bcrypt-password-mapper.enabled|false|If the bcrypt-password-mapper is enabled.
|quarkus.security.jdbc.principal-query."<name-principal-query>".bcrypt-password-mapper.password-index|1|The index (1 based numbering) of the column containing the password hash
|quarkus.security.jdbc.principal-query."<name-principal-query>".hashEncoding|BASE64|The password hash encoding ("BASE64" or "HEX")
|quarkus.security.jdbc.principal-query."<name-principal-query>".saltIndex| |The index (1 based numbering) of the column containing the password salt
|quarkus.security.jdbc.principal-query."<name-principal-query>".saltEncoding|BASE64|The salt encoding ("BASE64" or "HEX")
|quarkus.security.jdbc.principal-query."<name-principal-query>".roles.attribute-mappings."<named-attribute-mapping>".index|N/A| The index (1 based numbering) of column to map
|quarkus.security.jdbc.principal-query."<name-principal-query>".roles.attribute-mappings."<named-attribute-mapping>".to|N/A| The target attribute name
|===

## Future Work

* Propose more password mappers.
* Provide an opinionated configuration.

